import React, { useRef, useState, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useSnapshot } from "valtio";
import { useTexture, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { state } from "./store";
import { easing } from "maath";

export default function Droide(props) {
  const group = useRef();
  const [index, setIndex] = useState(1);
  const { nodes, materials, animations } = useGLTF(
    "/obj/lil-guy/lil_guy-transformed.glb"
  );
  const { ref, mixer, names, actions, clips } = useAnimations(animations);
  useEffect(() => {
    console.log(actions);
    // Reset and fade in animation after an index has been changed
    actions[names[index]].reset().fadeIn(0.5).play();
    // In the clean-up phase, fade it out
    return () => actions[names[index]].fadeOut(0.5);
  }, [index, actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-1.57, 0, 0]} scale={1.72}>
          <group
            name="fa0fa4fb139846b191f4783f719c8a10fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="lilGuy_Reference" position={[0, -0.37, 0.2]}>
                  <group
                    castShadow
                    ref={ref}
                    onClick={() => setIndex((index + 1) % names.length)}
                    name="Object_99"
                  >
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_102"
                      geometry={nodes.Object_102.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_102.skeleton}
                    />
                    <skinnedMesh
                      name="Object_104"
                      geometry={nodes.Object_104.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_104.skeleton}
                    />
                    <skinnedMesh
                      name="Object_106"
                      geometry={nodes.Object_106.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_106.skeleton}
                    />
                    <skinnedMesh
                      name="Object_108"
                      geometry={nodes.Object_108.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_108.skeleton}
                    />
                    <skinnedMesh
                      name="Object_110"
                      geometry={nodes.Object_110.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_110.skeleton}
                    />
                    <skinnedMesh
                      name="Object_112"
                      geometry={nodes.Object_112.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_112.skeleton}
                    />
                    <skinnedMesh
                      name="Object_114"
                      geometry={nodes.Object_114.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_114.skeleton}
                    />
                    <skinnedMesh
                      name="Object_116"
                      geometry={nodes.Object_116.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_116.skeleton}
                    />
                    <skinnedMesh
                      name="Object_118"
                      geometry={nodes.Object_118.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_118.skeleton}
                    />
                    <skinnedMesh
                      name="Object_120"
                      geometry={nodes.Object_120.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_120.skeleton}
                    />
                    <skinnedMesh
                      name="Object_122"
                      geometry={nodes.Object_122.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_122.skeleton}
                    />
                    <skinnedMesh
                      name="Object_124"
                      geometry={nodes.Object_124.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_124.skeleton}
                    />
                    <skinnedMesh
                      name="Object_126"
                      geometry={nodes.Object_126.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_126.skeleton}
                    />
                    <skinnedMesh
                      name="Object_128"
                      geometry={nodes.Object_128.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_128.skeleton}
                    />
                    <skinnedMesh
                      name="Object_130"
                      geometry={nodes.Object_130.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_130.skeleton}
                    />
                    <skinnedMesh
                      name="Object_132"
                      geometry={nodes.Object_132.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_132.skeleton}
                    />
                    <skinnedMesh
                      name="Object_134"
                      geometry={nodes.Object_134.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_134.skeleton}
                    />
                    <skinnedMesh
                      name="Object_136"
                      geometry={nodes.Object_136.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_136.skeleton}
                    />
                    <skinnedMesh
                      name="Object_138"
                      geometry={nodes.Object_138.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_138.skeleton}
                    />
                    <skinnedMesh
                      name="Object_140"
                      geometry={nodes.Object_140.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_140.skeleton}
                    />
                    <skinnedMesh
                      name="Object_142"
                      geometry={nodes.Object_142.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_142.skeleton}
                    />
                    <skinnedMesh
                      name="Object_144"
                      geometry={nodes.Object_144.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_144.skeleton}
                    />
                    <skinnedMesh
                      name="Object_146"
                      geometry={nodes.Object_146.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_146.skeleton}
                    />
                    <skinnedMesh
                      name="Object_148"
                      geometry={nodes.Object_148.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_148.skeleton}
                    />
                    <skinnedMesh
                      name="Object_150"
                      geometry={nodes.Object_150.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_150.skeleton}
                    />
                    <skinnedMesh
                      name="Object_152"
                      geometry={nodes.Object_152.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_152.skeleton}
                    />
                    <skinnedMesh
                      name="Object_154"
                      geometry={nodes.Object_154.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_154.skeleton}
                    />
                    <skinnedMesh
                      name="Object_156"
                      geometry={nodes.Object_156.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_156.skeleton}
                    />
                    <skinnedMesh
                      name="Object_158"
                      geometry={nodes.Object_158.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_158.skeleton}
                    />
                    <skinnedMesh
                      name="Object_160"
                      geometry={nodes.Object_160.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_160.skeleton}
                    />
                    <skinnedMesh
                      name="Object_162"
                      geometry={nodes.Object_162.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_162.skeleton}
                    />
                    <skinnedMesh
                      name="Object_164"
                      geometry={nodes.Object_164.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_164.skeleton}
                    />
                    <skinnedMesh
                      name="Object_166"
                      geometry={nodes.Object_166.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_166.skeleton}
                    />
                    <skinnedMesh
                      name="Object_168"
                      geometry={nodes.Object_168.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_168.skeleton}
                    />
                    <skinnedMesh
                      name="Object_170"
                      geometry={nodes.Object_170.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_170.skeleton}
                    />
                    <skinnedMesh
                      name="Object_172"
                      geometry={nodes.Object_172.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_172.skeleton}
                    />
                    <skinnedMesh
                      name="Object_174"
                      geometry={nodes.Object_174.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_174.skeleton}
                    />
                    <skinnedMesh
                      name="Object_176"
                      geometry={nodes.Object_176.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_176.skeleton}
                    />
                    <skinnedMesh
                      name="Object_178"
                      geometry={nodes.Object_178.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_178.skeleton}
                    />
                    <skinnedMesh
                      name="Object_180"
                      geometry={nodes.Object_180.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_180.skeleton}
                    />
                    <skinnedMesh
                      name="Object_182"
                      geometry={nodes.Object_182.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_182.skeleton}
                    />
                    <skinnedMesh
                      name="Object_184"
                      geometry={nodes.Object_184.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_184.skeleton}
                    />
                    <skinnedMesh
                      name="Object_186"
                      geometry={nodes.Object_186.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_186.skeleton}
                    />
                    <skinnedMesh
                      name="Object_188"
                      geometry={nodes.Object_188.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_188.skeleton}
                    />
                    <skinnedMesh
                      name="Object_190"
                      geometry={nodes.Object_190.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_190.skeleton}
                    />
                    <skinnedMesh
                      name="Object_192"
                      geometry={nodes.Object_192.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_192.skeleton}
                    />
                    <skinnedMesh
                      name="Object_194"
                      geometry={nodes.Object_194.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_194.skeleton}
                    />
                    <skinnedMesh
                      name="Object_196"
                      geometry={nodes.Object_196.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_196.skeleton}
                    />
                    <skinnedMesh
                      name="Object_198"
                      geometry={nodes.Object_198.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_198.skeleton}
                    />
                    <skinnedMesh
                      name="Object_200"
                      geometry={nodes.Object_200.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_200.skeleton}
                    />
                    <skinnedMesh
                      name="Object_202"
                      geometry={nodes.Object_202.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_202.skeleton}
                    />
                    <skinnedMesh
                      name="Object_204"
                      geometry={nodes.Object_204.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_204.skeleton}
                    />
                    <skinnedMesh
                      name="Object_206"
                      geometry={nodes.Object_206.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_206.skeleton}
                    />
                    <skinnedMesh
                      name="Object_208"
                      geometry={nodes.Object_208.geometry}
                      material={materials.robot_MTL}
                      skeleton={nodes.Object_208.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/obj/lil-guy/lil_guy-transformed.glb");
